version: '3.7'

services:
  app:
    build: app
    ports:
      - 80:5050
    networks:
      - db-network
    depends_on:
      - 'db'
    command: ["./wait-for-it.sh","db:5432","--","./start_app.sh"]

  db:
    image: postgres:13
    restart: always
    networks:
      - db-network
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=main
      - PGPORT=5432

networks:
  db-network:
    driver: bridge