version: '3.7'

services:
  app:
    build: app
    ports:
      - 5050:5050
    networks:
      - db-network
    depends_on:
      - 'db'
    command: ["./wait-for-it.sh", "db:5432", "--", "./start_app.sh"]
  nginx:
    image: nginx:1.19-alpine
    ports:
      - "80:80"
      - "443:443"
    networks:
      - db-network
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/cache:/etc/nginx/cache
      -  /etc/letsencrypt:/etc/letsencrypt

  db:
    image: postgres:13
    restart: always
    networks:
      - db-network
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=main
      - PGPORT=5432

networks:
  db-network:
    driver: bridge
